### ISSUE TITLE
【游戏语料】【持续更新】米厂全家桶（原、鸣、星）

### ISSUE THREAD

**Issue by voidf** [mnbvc-parallel-corpus-team/parallel_corpus_mnbvc#83]
派给Mr.B，这些语料来自 **Dimbreath**

- 鸣潮：github.com /Dimbreath/WutheringData/tree/master
- O神：gitlab.com /Dimbreath/AnimeGameData/
- 崩铁：github.com /Dimbreath/StarRailData

**Comment by Wzixiao** [comment]
10-26
鸣潮, 以整理完毕，71MB.

 @voidf 在之后需要在issues记录一下之前发布的时间.

**Comment by voidf** [comment]
https://github.com/ZHONG1011/GS_data_processing_MNBVC
